name: Employee Portal CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Backend Packages
        run: |
          cd backend
          npm install

      - name: Docker Build
        run: |
          cd backend
          docker build -t employee-backend .